%%{init: {'flowchart': {'htmlLabels': false, 'curve': 'linear'}} }%%
flowchart TD
    S([寮€濮媇)
    A{L1 闈炵┖?}
    B[鍙?L1 骞剁潯鐪燷
    C{闇€闄嶇骇?}
    D[鍏?L2]
    E{L2 闈炵┖?}
    F[鍙?L2 骞剁潯鐪燷
    G{闇€闄嶇骇?}
    H[鍏?L3]
    I{L3 闈炵┖?}
    J[鍙?L3 骞剁潯鐪燷
    K[join]
    L([缁撴潫:杩斿洖浠诲姟])
    Z([缁撴潫:杩斿洖绌篯)

    S --> A
    A -->|鏄瘄 B --> C
    C -->|鏄瘄 D --> K
    C -->|鍚 K
    A -->|鍚 E
    E -->|鏄瘄 F --> G
    G -->|鏄瘄 H --> K
    G -->|鍚 K
    E -->|鍚 I
    I -->|鏄瘄 J --> K
    I -->|鍚 Z
    K --> L
