%%{init: {'flowchart': {'htmlLabels': false, 'curve': 'linear'}} }%%
flowchart TD
    S([寮€濮媇)
    A[娴?FCFS 鑰楁椂]
    B[娴?Priority 鑰楁椂]
    C[娴?RR 鑰楁椂]
    D[娴?MLFQ 鑰楁椂]
    E[鍙栨渶灏忕瓥鐣
    F[杈撳嚭閫変腑鏃ュ織]
    G([缁撴潫:杩斿洖绛栫暐])

    S --> A --> B --> C --> D --> E --> F --> G
