%%{init: {'flowchart': {'htmlLabels': false, 'curve': 'linear'}} }%%
flowchart TD
    S([寮€濮媇)
    A{鏄惁浼樺厛绛栫暐?}
    B[鎸変紭鍏堥檷搴忔帓搴廬
    C[淇濇寔鍘熼『搴廬
    D([缁撴潫:杩斿洖鍒楄〃])

    S --> A
    A -->|鏄瘄 B --> D
    A -->|鍚 C --> D
