%%{init: {'flowchart': {'htmlLabels': false, 'curve': 'linear'}} }%%
flowchart TD
    S([寮€濮媇)
    A[鐢宠璁稿彲]
    B{璁稿彲鍙敤?}
    C[闃诲绛夊緟]
    D[杩涘叆涓寸晫鎵ц]
    E[閲婃斁璁稿彲]
    F([缁撴潫])

    S --> A --> B
    B -->|鍚 C --> B
    B -->|鏄瘄 D --> E --> F
