%%{init: {'flowchart': {'htmlLabels': false, 'curve': 'linear'}} }%%
flowchart TD
    S([寮€濮媇)
    A{running?}
    B[鎵撳嵃蹇収]
    C[sleep 鍛ㄦ湡]
    D{涓柇?}
    E([缁撴潫])

    S --> A
    A -->|鍚 E
    A -->|鏄瘄 B --> C --> D
    D -->|鏄瘄 E
    D -->|鍚 A
