%%{init: {'flowchart': {'htmlLabels': false, 'curve': 'linear'}} }%%
flowchart TD
    S([寮€濮媇)
    A{鍒楄〃绌?}
    B[鏍囪鎻愪氦]
    C[鎷╀紭绛栫暐]
    D[瑁呴厤璧勬簮涓庢睜]
    E[鍚姩鐩戞帶]
    F[鎺掑簭骞舵彁浜
    G[绛夊緟缁撴潫]
    H{瓒呮椂?}
    I[寮哄仠鍏滃簳]
    J[鍋滅洃鎺
    K[杈撳嚭鎶ヨ〃]
    L([缁撴潫])

    S --> A
    A -->|鏄瘄 L
    A -->|鍚 B --> C --> D --> E --> F --> G --> H
    H -->|鏄瘄 I --> J
    H -->|鍚 J
    J --> K --> L
